travis:
  secure:
    BINSTAR_TOKEN: INFpjt3WePKjv8LpMGCMx4UplCB69BNcwAr/q2CB+qOiy4SYVeNFSxQ+gBuPu5hLAPZBcG0RkbIxxUdvzOeKHh/6c+Vi3haxsxyw2RVIByq+eqG9LK1gSwZypc6+IIOGrpc+ktbwBFf6c/o2t5TUNAnPlVtGOVKaj5aWgBtXx870ImMSO/dEIUeUqAuEo76RPNbMLeGNi/Lh+MybHhHho4bBKNT0sxtJbWT970RAUFlnjxKsF8hqmyw087qQD092jm3A5w88J46yYVqMGhkCgnmTKkKyORMkPTFMTzYhVAcnLBtmTcC9MlYe/GxQGwGk2XClC4fgMWF4Db/lfvMa1B0JTc7LhL2csmT3U5fKskGUuzS1ho7iOclvhaurqWLVbSdv2O7zKc00mcovoOGw+IHw+oBZyBE57lFzaO2RPk3qPkKsNeojtGUNb5sFBPHDUN+JzYJDv7BSEVATfE0P9uvghjgmSP527RbVCyi3yYpqnGPawEXOx8TJKEV4tosc0CLldjPQSwns0fH1zhoJlYIZ51x3iGamFL83eN/DKlsRVpqfUkD80YR8VeuxGw1Fbqv/JJ4YPgCa4q7+MHWkEQNCpTTBlxT1INbZYPLNHeF/COYs5p5mKiKqV9CmDNWpJYzREvOi06je7nZWyuKS57mKOyJlFR7QQXSUDEFBeHg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
